Update Task 1

diff --git a/Task 1 b/Task 1
--- a/Task 1
+++ b/Task 1
@@ -1,85 +1,136 @@
 #!/bin/bash
 
-# Функция для вывода справки
-function show_help {
-    echo "Использование: $0 [OPTIONS]"
-    echo ""
-    echo "OPTIONS:"
-    echo "  -u, --users        Показать пользователей и их домашние директории"
-    echo "  -p, --processes    Показать запущенные процессы"
-    echo "  -h, --help         Показать эту справку"
-    echo "  -l PATH, --log PATH    Записать вывод в файл по указанному пути"
-    echo "  -e PATH, --errors PATH  Записать ошибки в файл по указанному пути"
-}
-
-# Функция для вывода пользователей и их домашних директорий
 function list_users {
-    if [[ -n "$log_file" ]]; then
-        getent passwd | awk -F: '{print $1, $6}' | sort > "$log_file" 2>>"$error_file"
-    else
-        getent passwd | awk -F: '{print $1, $6}' | sort
-    fi
+    echo "List of users"
+    awk -F':' '{ print $1, $6 }' /etc/passwd | sort
 }
 
-# Функция для вывода запущенных процессов
+#   awk: это утилита для обработки текстовых данных.
+#   -F':': устанавливает символ : в качестве разделителя полей. В файле /etc/passwd каждый пользователь представлен строкой, где данные разделены двоеточиями.
+#   '{ print $1, $6 }': команда awk, которая выводит первое ($1) и шестое ($6) поля для каждой строки:
+#       $1 — это имя пользователя.
+#       $6 — это домашний каталог пользователя.
+
 function list_processes {
-    if [[ -n "$log_file" ]]; then
-        ps -eo pid,comm --sort=pid > "$log_file" 2>>"$error_file"
-    else
-        ps -eo pid,comm --sort=pid
-    fi
+    echo "List of processes"
+    ps -eo pid,comm --sort=pid
 }
 
-# Обработка аргументов командной строки
-log_file=""
-error_file=""
-while getopts ":u:p:hl:e:" opt; do
+#    ps: команда для отображения информации о текущих процессах.
+#   -e: этот параметр говорит команде ps, что нужно отобразить все процессы, запущенные в системе, а не только процессы текущего пользователя.
+#   -o: указывает формат вывода. В данном случае, указываются поля, которые будут выводиться.
+#    pid: идентификатор процесса (Process ID).
+#    comm: имя команды или процесса.
+#    --sort=pid: сортирует вывод по идентификатору процесса (PID) в порядке возрастания.
+
+# функция для вывода подсказок (справки) о командах
+function show_help {
+    echo "Uasge: $0 [options]"
+    echo "Options:"
+    echo "  -u, --users            List users and their home directories"
+    echo "  -p, --processes        List running processes"
+    echo "  -h, --help             Show this help message"
+    echo "  -l PATH, --log PATH    Redirect output to a file at PATH"
+    echo "  -e PATH, --errors PATH Redirect error output to a file at PATH"
+}
+
+log_path=""
+error_path=""
+
+# getopts анализирует (парсит) опции и аргументы команд, которые были переданы
+# $OPTIND - индекс опции; $OPTARG - доп. аргумент опции.
+# символ двоеточия, следующий за именем опции, указывает на то, что она имеет доп. арг (в нашем случае l, e, -)
+while getopts ":uphl:e:-:" opt; do
     case $opt in
         u)
-            list_users
-            exit 0
+            action="users"
             ;;
         p)
-            list_processes
-            exit 0
+            action="processes"
             ;;
         h)
             show_help
             exit 0
             ;;
         l)
-            log_file="$OPTARG"
+            log_path="$OPTARG"
             ;;
         e)
-            error_file="$OPTARG"
+            error_path="$OPTARG"
+            ;;
+        # я крч в инете так нашел. наверное можно было как-то иначе, но вроде работает и ладно.
+        -)
+            case "${OPTARG}" in
+            users)
+                action="users"
+                ;;
+            processes)
+                action="processes"
+                ;;
+            help)
+                show_help
+                exit 0
+                ;;
+            log)
+                log_path="${!OPTIND}"; OPTIND=$(( OPTIND + 1 ))
+                ;;
+            errors)
+                error_path="${!OPTIND}"; OPTIND=$(( OPTIND + 1 ))
+                ;;
+             *)
+                echo "Invalid option: --${OPTARG}" >&2
+                exit 1
+                ;;
+            esac
             ;;
         \?)
-            echo "Неверный параметр: -$OPTARG" >&2
-            show_help
+            echo "Invalid opion: -$OPTARG" >&2
             exit 1
             ;;
         :)
-            echo "Опция -$OPTARG требует аргумент." >&2
-            show_help
+            echo "Option -$OPTARG requirs an argument." >&2
             exit 1
             ;;
     esac
 done
 
-# Проверка на наличие лог-файла и прав на запись
-if [[ -n "$log_file" && ! -w "$(dirname "$log_file")" ]]; then
-    echo "Ошибка: Нет прав на запись в файл $log_file" >&2
-    exit 1
+# &> перенаправляет stdout, stderr в один файл
+# >&2 перенаправляет stdout в stderr
+# 2> перенаправляет stderr в указанный файл
+# dev/null - спец. файл "черная дыра"
+
+# Доступность путей
+if [[ -n $log_path ]]; then
+    if ! touch "$log_path" &> /dev/null; then
+        echo "Can not write to log file: $log_path" >&2
+        exit 1
+    fi
+    exec > "$log_path"
 fi
 
-# Проверка на наличие файла для ошибок и прав на запись
-if [[ -n "$error_file" && ! -w "$(dirname "$error_file")" ]]; then
-    echo "Ошибка: Нет прав на запись в файл $error_file" >&2
-    exit 1
+if [[ -n $error_path ]]; then
+    if ! touch "$error_path" &> /dev/null; then
+        echo "Can not write to log file: $error_path" >&2
+        exit 1
+    fi
+    exec 2> "$error_path"
 fi
 
-# Если не указаны аргументы, выводим справку
-if [[ -z "$log_file" && -z "$error_file" ]]; then
-    show_help
-    exit 1
-fi
+
+# типа после присвоения 'action' какого-то параметра, можно что-то делать
+case $action in
+    users)
+        list_users
+        ;;
+    processes)
+        list_processes
+        ;;
+    *)
+        echo "Error." >&2
+        show_help
+        exit 1
+        ;;
+esac
+
+# Это пример работы для -e. Эта команда вызывает ошибку, и она отправиться в error.log
+# ls noneexistent_file
